name: Terraform EC2 Instance

on:
  workflow_dispatch:
    inputs:
      instance_name:
        description: 'Name for the EC2 instance'
        required: true
        default: 'my-ec2-instance'
  push:
    branches:
      - main # Or your main branch

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.7.4 # Specify your desired Terraform version

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan -var="ec2_name=${{ github.event.inputs.instance_name }}"
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        if: github.event.inputs.apply_changes == 'true' # Add a conditional input to apply
        run: terraform apply -auto-approve tfplan
        continue-on-error: true

      - name: Terraform Destroy
        if: github.event.inputs.destroy_changes == 'true'
        run: terraform destroy -auto-approve
